import React, { useEffect, useRef, useState } from "react";
import { v4 as uuid } from "uuid";
import { format } from "date-fns";
import { FiSend, FiCheck, FiCheckCircle } from "react-icons/fi";

const Header = () => (
  <div className="header">
      <div className="title">
            <span className="status-dot online"></span>
                  Chat with <b>Me</b>
                      </div>
                          <div className="subtitle">Demo UI (real-time comes next)</div>
                            </div>
                            );

                            const MessageBubble = ({ text, from, time, read }) => {
                              const isMe = from === "me";
                                return (
                                    <div className={`row ${isMe ? "right" : "left"}`}>
                                          <div className={`bubble ${isMe ? "mine" : "theirs"}`}>
                                                  <div className="text">{text}</div>
                                                          <div className="meta">
                                                                    <span>{format(time, "HH:mm")}</span>
                                                                              {isMe && (
                                                                                          <span className={`ticks ${read ? "read" : "sent"}`}>
                                                                                                        {read ? <FiCheckCircle /> : <FiCheck />}
                                                                                                                    </span>
                                                                                                                              )}
                                                                                                                                      </div>
                                                                                                                                            </div>
                                                                                                                                                </div>
                                                                                                                                                  );
                                                                                                                                                  };

                                                                                                                                                  export default function Chat() {
                                                                                                                                                    const [msg, setMsg] = useState("");
                                                                                                                                                      const [messages, setMessages] = useState([
                                                                                                                                                          {
                                                                                                                                                                id: uuid(),
                                                                                                                                                                      text: "Hi! This is the new chat UI. Type below 👇",
                                                                                                                                                                            from: "them",
                                                                                                                                                                                  time: new Date(),
                                                                                                                                                                                        read: true,
                                                                                                                                                                                            },
                                                                                                                                                                                              ]);

                                                                                                                                                                                                const listRef = useRef(null);

                                                                                                                                                                                                  useEffect(() => {
                                                                                                                                                                                                      // auto-scroll to bottom on new messages
                                                                                                                                                                                                          if (listRef.current) listRef.current.scrollTop = listRef.current.scrollHeight;
                                                                                                                                                                                                            }, [messages]);

                                                                                                                                                                                                              const sendMessage = () => {
                                                                                                                                                                                                                  const text = msg.trim();
                                                                                                                                                                                                                      if (!text) return;

                                                                                                                                                                                                                          const myMsg = {
                                                                                                                                                                                                                                id: uuid(),
                                                                                                                                                                                                                                      text,
                                                                                                                                                                                                                                            from: "me",
                                                                                                                                                                                                                                                  time: new Date(),
                                                                                                                                                                                                                                                        read: false, // becomes true after “seen”
                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                setMessages((prev) => [...prev, myMsg]);
                                                                                                                                                                                                                                                                    setMsg("");

                                                                                                                                                                                                                                                                        // Fake "read" and reply (we’ll replace with Firebase later)
                                                                                                                                                                                                                                                                            setTimeout(() => {
                                                                                                                                                                                                                                                                                  // mark my last message read
                                                                                                                                                                                                                                                                                        setMessages((prev) =>
                                                                                                                                                                                                                                                                                                prev.map((m) => (m.id === myMsg.id ? { ...m, read: true } : m))
                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                          }, 800);

                                                                                                                                                                                                                                                                                                              setTimeout(() => {
                                                                                                                                                                                                                                                                                                                    setMessages((prev) => [
                                                                                                                                                                                                                                                                                                                            ...prev,
                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                              id: uuid(),
                                                                                                                                                                                                                                                                                                                                                        text: "Got it! (This is a demo reply 🤖).",
                                                                                                                                                                                                                                                                                                                                                                  from: "them",
                                                                                                                                                                                                                                                                                                                                                                            time: new Date(),
                                                                                                                                                                                                                                                                                                                                                                                      read: true,
                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                    ]);
                                                                                                                                                                                                                                                                                                                                                                                                        }, 1200);
                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                            const onKey = (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                if (e.key === "Enter") sendMessage();
                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="wrap">
                                                                                                                                                                                                                                                                                                                                                                                                                              <Header />
                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="messages" ref={listRef}>
                                                                                                                                                                                                                                                                                                                                                                                                                                            {messages.map((m) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <MessageBubble key={m.id} {...m} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="composer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={msg}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setMsg(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onKeyDown={onKey}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Type a message"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={sendMessage} aria-label="Send">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <FiSend size={22} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        